[package]
name = "portal"
version = "0.1.0"
authors = ["Kolby ML (Moroz Liebl) <kolbydml@gmail.com>"]
edition = "2021"

[dependencies]
alloy-rlp = "0.3.8"
alloy-primitives = "0.8.3"
ethportal-api = { git = "https://github.com/ethereum/trin", rev = "72f144e8e63751eac5c667753b47a4eda9cb9fea" }
futures = "0.3.25"
hivesim = { git = "https://github.com/ethereum/hive", rev = "4408fc1de3fee3ac23acd25a812c117756af2f39" }
itertools = "0.10.5"
serde_json = "1.0.95"
serde_yaml = "0.9.33"
tokio = { version = "1.14.0", features = ["full"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.16"

