version: 2.1
orbs:
  go: circleci/go@1.5.0
  slack: circleci/slack@4.10.1

jobs:
  # This job builds the hive executable and stores it in the workspace.
  build:
    docker:
      - image: cimg/go:1.18
    steps:
      # Build it.
      - checkout
      - go/load-cache
      - go/mod-download
      - go/save-cache
      - run: {command: "go build ."}
      # Store the executable.
      - persist_to_workspace:
          root: .
          paths: ["hive"]

  # This job runs the optimism test simulations. This requires a virtual
  # machine instead of the container-based build environment because hive needs
  # to be able to talk to the docker containers it creates.
  hive-rpc-tests:
    machine:
      image: ubuntu-2004:202201-02
    steps:
      - checkout
      - attach_workspace: {at: "/tmp/build"}
      - run:
          command: "/tmp/build/hive -sim=optimism/rpc -client=go-ethereum,op-geth,op-proposer,op-batcher,op-node,op-contracts |& tee /tmp/build/hive-rpc.log"
      - run:
          command: "! grep 'pass.*=false' /tmp/build/hive-rpc.log"
      - slack/notify:
          channel: C03N11M0BBN
          event: fail
          template: basic_fail_1
      - slack/notify:
          channel: C03N11M0BBN
          event: pass
          template: basic_success_1

  hive-testnet-tests:
    machine:
      image: ubuntu-2004:202201-02
    steps:
      - checkout
      - attach_workspace: {at: "/tmp/build"}
      - run:
          command: "/tmp/build/hive -sim=optimism/testnet -client=go-ethereum,op-geth,op-proposer,op-batcher,op-node,op-contracts |& tee /tmp/build/hive-testnet.log"
      - run:
          command: "! grep 'pass.*=false' /tmp/build/hive-testnet.log"
      - slack/notify:
          channel: C03N11M0BBN
          event: fail
          template: basic_fail_1
      - slack/notify:
          channel: C03N11M0BBN
          event: pass
          template: basic_success_1

  hive-p2p-tests:
    machine:
      image: ubuntu-2004:202201-02
    steps:
      - checkout
      - attach_workspace: {at: "/tmp/build"}
      - run:
          command: "/tmp/build/hive -sim=optimism/p2p -client=go-ethereum,op-geth,op-proposer,op-batcher,op-node,op-contracts |& tee /tmp/build/hive-p2p.log"
      - run:
          command: "! grep 'pass.*=false' /tmp/build/hive-p2p.log"
      - slack/notify:
          channel: C03N11M0BBN
          event: fail
          template: basic_fail_1
      - slack/notify:
          channel: C03N11M0BBN
          event: pass
          template: basic_success_1

  # This job runs the go unit tests.
  go-test:
    docker:
      - image: cimg/go:1.18
    steps:
      # Get the source.
      - checkout
      - go/load-cache
      - go/mod-download
      - go/save-cache
      # Run the tests.
      - run:
          name: "hive module tests"
          command: "go test -cover ./..."
      - run:
          name: "hiveproxy module tests"
          command: "go test -cover ./..."
          working_directory: "./hiveproxy"
      - run:
          name: "Compile Go simulators"
          command: ".circleci/compile-simulators.sh"

workflows:
  main:
    jobs:
      - go-test
      - build
      - hive-rpc-tests:
          requires: ["build"]
          context: slack
      - hive-testnet-tests:
          requires: ["build"]
          context: slack
      - hive-p2p-tests:
          requires: ["build"]
          context: slack
