- client: besu
  nametag: cancun-git
  dockerfile: git
  build_args:
      github: hyperledger/besu
      tag: main

- client: erigon
  nametag: cancun-git
  dockerfile: git
  build_args:
      github: ledgerwatch/erigon
      tag: devel

- client: ethereumjs
  nametag: cancun-git
  build_args:
      github: ethereumjs/ethereumjs-monorepo
      tag: master

- client: go-ethereum
  nametag: cancun-git
  dockerfile: git

- client: nethermind
  nametag: cancun-git
  dockerfile: git
  build_args:
      github: NethermindEth/nethermind
      tag: master

- client: reth
  nametag: cancun-git
  dockerfile: git
  build_args:
    github: paradigmxyz/reth
    tag: main

- client: teku-bn
  nametag: deneb
  build_args:
      baseimage: ethpandaops/teku
      tag: master
- client: teku-vc
  nametag: deneb
  build_args:
      baseimage: ethpandaops/teku
      tag: master

- client: prysm-bn
  nametag: deneb
  build_args:
      baseimage: ethpandaops/prysm
      tag: develop-linux-amd64
- client: prysm-vc
  nametag: deneb
  build_args:
      baseimage: ethpandaops/prysm-validator
      tag: develop-linux-amd64

- client: lighthouse-bn
  nametag: deneb
  build_args:
      baseimage: ethpandaops/lighthouse
      tag: unstable-linux-amd64
- client: lighthouse-vc
  nametag: deneb
  build_args:
      baseimage: ethpandaops/lighthouse
      tag: unstable-linux-amd64

- client: lodestar-bn
  nametag: deneb
  build_args:
      baseimage: ethpandaops/lodestar
      tag: unstable-linux-amd64
- client: lodestar-vc
  nametag: deneb
  build_args:
      baseimage: ethpandaops/lodestar
      tag: unstable-linux-amd64

- client: nimbus-bn
- client: nimbus-vc
