- client: besu
  nametag: cancun-git
  dockerfile: git
  build_args:
      github: Gabriel-Trintinalia/besu
      tag: add-decode-type-to-transaction-decoder

- client: erigon
  nametag: cancun-git
  dockerfile: git
  build_args:
      github: ledgerwatch/erigon
      tag: devel

- client: ethereumjs
  nametag: cancun-git
  build_args:
      github: ethereumjs/ethereumjs-monorepo
      tag: master

- client: go-ethereum
  nametag: cancun-git
  dockerfile: git
  build_args:
      github: lightclient/go-ethereum
      tag: devnet-9

- client: nethermind
  nametag: cancun-git
  dockerfile: git
  build_args:
      github: NethermindEth/nethermind
      tag: cancun

- client: reth
  nametag: cancun-git
  dockerfile: git
  build_args:
    github: paradigmxyz/reth
    tag: main

- client: teku-bn
- client: teku-vc

- client: prysm-bn
  nametag: deneb
  build_args:
      baseimage: ethpandaops/prysm
      tag: develop-linux-amd64
- client: prysm-vc
  nametag: deneb
  build_args:
      baseimage: ethpandaops/prysm-validator
      tag: develop-linux-amd64

- client: lighthouse-bn
  nametag: deneb
  build_args:
      baseimage: sigp/lighthouse
      tag: deneb-modern
- client: lighthouse-vc
  nametag: deneb
  build_args:
      baseimage: sigp/lighthouse
      tag: deneb-modern

- client: lodestar-bn
  nametag: deneb
  build_args:
      baseimage: ethpandaops/lodestar
      tag: deneb-builder
- client: lodestar-vc
  nametag: deneb
  build_args:
      baseimage: ethpandaops/lodestar
      tag: deneb-builder

- client: nimbus-bn
- client: nimbus-vc
