- client: besu
  nametag: cancun-git
  dockerfile: git
  build_args:
      github: hyperledger/besu
      tag: main

- client: erigon
  nametag: cancun-git
  dockerfile: git
  build_args:
      github: ledgerwatch/erigon
      tag: devel

- client: ethereumjs
  nametag: cancun-git
  build_args:
      github: ethereumjs/ethereumjs-monorepo
      tag: hive-branch

- client: go-ethereum
  nametag: cancun-git
  dockerfile: git
  build_args:
      github: lightclient/go-ethereum
      tag: devnet-8

- client: nethermind
  nametag: cancun-git
  dockerfile: git
  build_args:
      github: NethermindEth/nethermind
      tag: cancun
